### ISSUE TITLE
Unable to authenticate on Azure China Cloud

### ISSUE THREAD

**Issue by jmapro** [turbot/steampipe-plugin-azuread#167]
**Describe the bug**
The authentication is done against AzureCloud endpoints instead of AzureChinaCloud endpoints, which leads to an authentication error as the account exists only in ChinaCloud.

```
Error: azuread: {"Code":"","Message":"AzureCLICredential: ERROR: AADSTS500011: The resource principal named https://graph.microsoft.com was not found in the tenant named ****REDACTED****. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 20a8654f-0517-4567-9d3d-ccb52392bc00 Correlation ID: 11fb67bf-6ba3-49d2-a07f-8ba2fef56cda Timestamp: 2023-12-21 16:48:31Z\nInteractive authentication is needed. Please run:\naz login --scope https://graph.microsoft.com/.default\n"} (SQLSTATE HV000)
```

The error shows that the API request is done on graph.microsoft.com instead of graph.chinacloudapi.cn

**Steampipe version (`steampipe -v`)**
v0.21.2

**Plugin version (`steampipe plugin list`)**
v0.15.0
Also tested with https://github.com/turbot/steampipe-plugin-azuread/pull/152 which upgrade the SDK.

**To reproduce**
1. Configure azuread to authenticate against AzureChinaCloud
2. Authenticate azure-cli on the tenant
3. Try a steampipe query on the Azure AD.

azuread.spc
```
connection "azuread" {
  plugin = "azuread"

  # Defaults to "AZUREPUBLICCLOUD". Valid environments are "AZUREPUBLICCLOUD", "AZURECHINACLOUD" and "AZUREUSGOVERNMENTCLOUD"
  environment = "AZURECHINACLOUD"
}
```

Commands
```
az cloud set --name AzureChinaCloud
az login
steampipe query "SELECT * FROM azuread.azuread_user"
```

**Expected behavior**
A list of Active directory users is shown.

**Additional context**

I can authenticate myself on AzureChina with the Azure steampipe plugin.

**Comment by ParthaI** [comment]
Thanks @jmapro, For bringing the issue to our attention and apologize for the inconvenience. I will take a look at the issue and let you know if I need anything else.

**Comment by misraved** [comment]
Apologies @jmapro and @pdecat for the radio silence on this issue.

I was examining the code to figure out the reason for the failure and I have a few questions based on my findings:
- Since nothing looked very suspicious in the plugin code, I explored the SDK issues for assistance and came across this [issue](https://github.com/Azure/azure-sdk-for-go/issues/21807). @pdecat, didn't the SDK update help in fixing the issue?
- Would it be possible to send the plugin logs (available in `.steampipe/logs/plugin_*`) for further analysis? Please make sure that you remove any sensitive values.

**Comment by misraved** [comment]
Thank you so much @jmapro for the logs 👍.

**Comment by bigdatasourav** [comment]
Hey @jmapro, Could you please execute the below sample code and see if you are getting the results -

Please run `az login --scope https://management.chinacloudapi.cn//.default`

```
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/subscriptions"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
	// Set the cloud environment to Azure China Cloud
	os.Setenv("AZURE_ENVIRONMENT", "AZURECHINACLOUD")

	// Create an authorizer from Azure CLI
	authorizer, err := auth.NewAuthorizerFromCLI()
	if err != nil {
		fmt.Printf("Failed to create authorizer: %v\n", err)
		return
	}

	// Create a subscriptions client
	subsClient := subscriptions.NewClientWithBaseURI(azure.ChinaCloud.ResourceManagerEndpoint)
	subsClient.Authorizer = authorizer

	// List subscriptions
	ctx := context.Background()
	result, err := subsClient.List(ctx)
	if err != nil {
		fmt.Printf("Failed to list subscriptions: %v\n", err)
		return
	}

	// Output the subscriptions
	for _, sub := range result.Values() {
		fmt.Printf("Subscription ID: %s, Name: %s\n", *sub.SubscriptionID, *sub.DisplayName)
	}
}

```

**Comment by jmapro** [comment]
Hi !

I have the list of available subscriptions as a result.



De : souravTurbot ***@***.***>
Date : jeudi, 4 avril 2024 à 06:45
À : turbot/steampipe-plugin-azuread ***@***.***>
Cc : Jeremy MARMOL ***@***.***>, Mention ***@***.***>
Objet : Re: [turbot/steampipe-plugin-azuread] Unable to authenticate on Azure China Cloud (Issue #167)

Hey @jmapro<https://github.com/jmapro>, Could you please execute the below sample code and see if you are getting the results -

Please run az login --scope https://management.chinacloudapi.cn//.default

package main



import (

        "context"

        "fmt"

        "os"



        "github.com/Azure/azure-sdk-for-go/profiles/latest/resources/mgmt/subscriptions"

        "github.com/Azure/go-autorest/autorest/azure"

        "github.com/Azure/go-autorest/autorest/azure/auth"

)



func main() {

        // Set the cloud environment to Azure China Cloud

        os.Setenv("AZURE_ENVIRONMENT", "AZURECHINACLOUD")



        // Create an authorizer from Azure CLI

        authorizer, err := auth.NewAuthorizerFromCLI()

        if err != nil {

               fmt.Printf("Failed to create authorizer: %v\n", err)

               return

        }



        // Create a subscriptions client

        subsClient := subscriptions.NewClientWithBaseURI(azure.ChinaCloud.ResourceManagerEndpoint)

        subsClient.Authorizer = authorizer



        // List subscriptions

        ctx := context.Background()

        result, err := subsClient.List(ctx)

        if err != nil {

               fmt.Printf("Failed to list subscriptions: %v\n", err)

               return

        }



        // Output the subscriptions

        for _, sub := range result.Values() {

               fmt.Printf("Subscription ID: %s, Name: %s\n", *sub.SubscriptionID, *sub.DisplayName)

        }

}

**Comment by bigdatasourav** [comment]
Great! Could you please try executing steampipe query with `az login --scope https://management.chinacloudapi.cn//.default` and `environment = "AZURECHINACLOUD"` and let know if it is working fine now?

**Comment by jmapro** [comment]
I still have the error with a steampipe query on Azure Graph API (AzureAD)

```
Error: azuread: {"Code":"","Message":"AzureCLICredential: ERROR: AADSTS500011: The resource principal named https://graph.microsoft.com was not found in the tenant named *******. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 0b00a1c7-a410-4e56-98d8-338aea692800 Correlation ID: d6bcc2e7-3009-4c1d-9757-1581c7424b59 Timestamp: 2024-04-04 08:44:30Z\nInteractive authentication is needed. Please run:\naz login --scope https://graph.microsoft.com/.default\n"} (SQLSTATE HV000)
```

It seems that the SDK does not reach the Chinese Graph API endpoint.

**Comment by bigdatasourav** [comment]
Thanks for the quick update! I have raised a [fix](https://github.com/turbot/steampipe-plugin-azuread/pull/174) which may solve the problem, Could you please try it out and let us know if it helps?

1. Clone the repository: git clone https://github.com/turbot/steampipe-plugin-azuread.git
2. Change directory: cd steampipe-plugin-azuread
3. Switch to the specific branch: git checkout china_cloud
4. Execute the make command: make
5. Run the query

**Comment by jmapro** [comment]
I still have the issue with the fix.

[azuread.log](https://github.com/turbot/steampipe-plugin-azuread/files/14881600/azuread.log)

**Comment by bigdatasourav** [comment]
Hey @jmapro, as per the SDK team suggestion I have updated the code and set the base URL, Could you please try now and let me know your feedback?

1. git pull origin china_cloud
2. Execute the make command: make
3. Run the query

**Comment by jmapro** [comment]
Hey ! 

There's a type in the URL. You forgot the "d" in chinacloudapi.

```
Error: azuread: {"Code":"","Message":"Get \"https://microsoftgraph.chinaclouapi.cn/v1.0/applications?$top=999\": dial tcp: lookup microsoftgraph.chinaclouapi.cn: no such host"} (SQLSTATE HV000)
```

**Comment by bigdatasourav** [comment]
Thank you for bringing that to my attention! I've corrected the typo. Please give it another try now.

**Comment by jmapro** [comment]
still no joy :( 

```
Error: azuread: {"Code":"","Message":"AzureCLICredential: ERROR: AADSTS500011: The resource principal named https://graph.microsoft.com was not found in the tenant named **********. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: f559d38a-a955-4466-8372-0ec01af94600 Correlation ID: d5e74ad2-e5ce-4225-8b80-00998fba4385 Timestamp: 2024-04-08 07:55:04Z\nInteractive authentication is needed. Please run:\naz login --scope https://graph.microsoft.com/.default\n"} (SQLSTATE HV000)
```

**Comment by bigdatasourav** [comment]
@jmapro, I have updated the Authentication provider also with the `chinacloud` scope, could you please take a pull and try it once?

**Comment by jmapro** [comment]
@bigdatasourav, It works ! 🎉 

Thanks a lot for your help

**Comment by bigdatasourav** [comment]
Great!! Thanks for your help with the testing 👍
